#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 25 13:44:47 2020

@author: pi
"""
import gallager_A_V2 as gal
import os
from scipy.io import savemat

matrices=os.listdir("matrices_alireza")

for matrix in matrices:
    obj=gal.paritycheck("matrices_alireza/"+matrices[0]) #Create the object
    mdic={"H":obj.H}
    savemat('matlab/{}.mat'.format(matrix[0:5 ]),mdic)